### ISSUE TITLE
Programar botón para recuperación de contraseña mediante las preguntas de recuperación 

### ISSUE THREAD

**Issue by QuesoMozzarella** [QuesoMozzarella/Clase9#1]
validar que se ingrese un documento valido para buscar la contraseña 
validar que el documento sea numérico
crear la clase usuario con sus 11 propiedades 
solo considerar un pasword 
buscar las preguntas para recuperar la contraseña

**Comment by penauts** [comment]
ok me voy a encargar de eso

**Comment by QuesoMozzarella** [comment]
quedo pendiente del push y el pull request

**Comment by QuesoMozzarella** [comment]
se cierra el issues # 1

**Comment by QuesoMozzarella** [comment]
Se cierra el issue # 1
